// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Statistics;
using Statistics.Entities;
using Statistics.Events;
using System;

namespace Statistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Statistics.Entities.LoginInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("From");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Statistics.Entities.NewsAdditionInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedTime");

                    b.Property<string>("Author");

                    b.HasKey("Id");

                    b.ToTable("NewsAdditions");
                });

            modelBuilder.Entity("Statistics.Entities.RequestInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From");

                    b.Property<int>("RequestType");

                    b.Property<DateTime>("Time");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Statistics.Entities.SubscriptionOperationInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<int>("Operation");

                    b.Property<string>("Subscriber");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionOperations");
                });

            modelBuilder.Entity("Statistics.Entities.UserOperationInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Operation");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("UserOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
